### ISSUE TITLE
(RH)EL 7 support

### ISSUE THREAD

**Issue by fuero** [domcleal/librarian-puppet-copr#1]
The packages provided build fine with mock against rhel-7-x86_64, but don't install.

Yum will complain like this:

```
--> Finished Dependency Resolution
Error: Package: rubygem-librarian-puppet-1.0.9-1.el7.noarch (/rubygem-librarian-puppet-1.0.9-1.el7.noarch)
           Requires: ruby(abi)
Error: Package: rubygem-librarian-0.1.2-1.el7.noarch (/rubygem-librarian-0.1.2-1.el7.noarch)
           Requires: ruby(abi)
```

There is a compatibility package around (https://gist.github.com/fandingo/5978700)
that makes it install on RHEL7.0.
The fix mentioned in the gist seems no good though, as the RHEL 7 package doesn't seem to provide `ruby(release)`:

```
# rpm -q --provides ruby
ruby = 2.0.0.353-20.el7
ruby(runtime_executable) = 2.0.0
ruby(x86-64) = 2.0.0.353-20.el7
# yum info ruby
[...]
Name        : ruby
Arch        : x86_64
Version     : 2.0.0.353
Release     : 20.el7
```

**Comment by domcleal** [comment]
Thanks for the report, I believe this is now fixed in the repo.  ruby(release) works fine, as it's provided by ruby-libs rather than ruby, so I've updated all of the packages to depend on it.
