### ISSUE TITLE
mention the need of git-annex branch

### ISSUE THREAD

**Issue by marcindulak** [domcleal/librarian-puppet-copr#2]
Recently I've been trying to use tito + git-annex for a multi-package copr project, and your repo together with https://m0dlx.com/blog/Reproducible_builds_on_Copr_with_tito_and_git_annex.html provided the best documentation available. However your repo does not include a git-annex branch needed for copr builds to work. Adding this note for reference.

**Comment by domcleal** [comment]
I don't think it's necessary, what happens when you use this repo without it?

**Comment by marcindulak** [comment]
https://lists.fedoraproject.org/archives/list/copr-devel@lists.fedorahosted.org/thread/HKX4HBBB4DV2VX75LFTR7DZW66BZ3R2T/

If you don't have the git-annex branch, tito will fail like this (the long traceback ommited):

```
cd /tmp/
git clone https://github.com/domcleal/librarian-puppet-copr
cd librarian-puppet-copr/rubygem-highline/
tito build --srpm
Creating output directory: /tmp/tito
Checking for tag [rubygem-highline-1.6.21-2] in git repo [https://github.com/domcleal/librarian-puppet-copr]
Building package [rubygem-highline-1.6.21-2]
ERROR: Error running command: git-annex lock
...
```

**Comment by domcleal** [comment]
Right, but you would first run `git annex init`, have you done that? `setup_sources.sh` (which is in the README) will tell you to do so.

**Comment by marcindulak** [comment]
https://git-annex.branchable.com/tips/centralized_git_repository_tutorial/on_GitHub/ says 
" push the git-annex branch, which is used to track the file contents"

    git push origin master git-annex

Also https://docs.pagure.org/copr.copr/user_documentation.html#tito goes directly from a git checkout to a tito command.

**Comment by domcleal** [comment]
The branch has no purpose here, as a shared source isn't used. It uses the special web source, which is configured by using setup_sources.sh. There's no point in me pushing a git-annex branch. Please use the instructions in the README to set this repo up on clone.

**Comment by marcindulak** [comment]
https://github.com/domcleal/librarian-puppet-copr/blob/master/setup_sources.sh will work manually, but copr does not do those steps, it does something like https://docs.pagure.org/copr.copr/user_documentation.html#tito:

```
$ git clone <provided git url> result.git
$ cd result.git
$ git checkout <provided branch> # optional
$ tito build --srpm
```
The question is how one gets your repo to build in copr using tito?

**Comment by domcleal** [comment]
Using tito's copr releaser, which uploads an SRPM: https://github.com/domcleal/librarian-puppet-copr/blob/master/rel-eng/releasers.conf

**Comment by marcindulak** [comment]
OK, it's a different use case then.
